"""Removed old fields

Revision ID: e33819a5e98d
Revises: af979caa394e
Create Date: 2026-06-10 18:40:14.943743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33819a5e98d'
down_revision: Union[str, None] = 'af979caa394e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_tokens', 'ipfs_hash')
    op.drop_column('service_tokens', 'has_ipfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tokens', sa.Column('has_ipfs', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('service_tokens', sa.Column('ipfs_hash', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
