"""Added ipfs fields to token

Revision ID: af979caa394e
Revises: 8cafaaed954a
Create Date: 2026-06-10 18:18:46.951095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af979caa394e'
down_revision: Union[str, None] = '8cafaaed954a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tokens', sa.Column('ipfs_hash', sa.Integer(), nullable=True))
    op.add_column('service_tokens', sa.Column('has_ipfs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_tokens', 'has_ipfs')
    op.drop_column('service_tokens', 'ipfs_hash')
    # ### end Alembic commands ###
