"""Added metadata field

Revision ID: 8cafaaed954a
Revises: d9f1c13394ab
Create Date: 2026-06-08 17:57:18.015990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cafaaed954a'
down_revision: Union[str, None] = 'd9f1c13394ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tokens', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_tokens', 'data')
    # ### end Alembic commands ###
