"""Fixed types

Revision ID: 3555e9b2c75f
Revises: e33819a5e98d
Create Date: 2026-06-10 18:40:31.693285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3555e9b2c75f'
down_revision: Union[str, None] = 'e33819a5e98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tokens', sa.Column('ipfs_hash', sa.String(), nullable=True))
    op.add_column('service_tokens', sa.Column('has_ipfs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_tokens', 'has_ipfs')
    op.drop_column('service_tokens', 'ipfs_hash')
    # ### end Alembic commands ###
